SPAWN:New('MiG21 Group 1')
    :InitKeepUnitNames(false)
    :InitLimit(2, 500)
    :InitDelayOff()
    :InitSkill("Random")
    :InitRepeatOnLanding()
    :SpawnScheduled(600, .3)

SPAWN:New('MiG29 Group 1')
  :InitKeepUnitNames(false)
  :InitLimit(3, 500)
  :InitDelayOff()
  :InitSkill("Random")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)

SPAWN:New('Su27 Group 1')
  :InitKeepUnitNames(false)
  :InitLimit(2, 500)
  :InitDelayOff()
  :InitSkill("Random")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)

SPAWN:New('Su27 Group 2')
  :InitKeepUnitNames(false)
  :InitLimit(4, 500)
  :InitDelayOff()
  :InitSkill("Random")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)

SPAWN:New('Su27 Group 3')
  :InitKeepUnitNames(false)
  :InitLimit(1, 500)
  :InitDelayOff()
  :InitSkill("Random")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)

SPAWN:New('Su27 Group 4')
  :InitKeepUnitNames(false)
  :InitLimit(2, 500)
  :InitDelayOff()
  :InitSkill("Random")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)

SPAWN:New('Su33 Group 1')
  :InitKeepUnitNames(false)
  :InitLimit(3, 500)
  :InitDelayOff()
  :InitSkill("Random")
  :InitRepeatOnLanding()
  :SpawnScheduled(600, .3)